import {useEffect} from 'react';
import Head from 'next/head';
import ContentWrapper from '../../components/ContentWrapper';
import {useDispatch, useSelector} from 'react-redux';
import {citiesFetch} from '../../redux/actions/cities';
import CityCard from '../../components/CityCard';
import styles from '../../styles/CitiesList.module.css';


export default function CitiesList() {
    const dispatch = useDispatch();
    const citiesIds = useSelector(state => state.cities.citiesIds);

    useEffect(() => {
        dispatch(citiesFetch());
    }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentWrapper>
          <div className={styles.card__wrapper}>
            {citiesIds && citiesIds.map(id => (
                <CityCard key={id} id={id}/>
            ))}
          </div>
      </ContentWrapper>
    </div>
  )
}