export const DATA_FETCH_START = "DATA_FETCH_START";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_ERROR = "DATA_FETCH_ERROR";
export const DATA_FETCH_REFRESH = "DATA_FETCH_REFRESH";