export const PLACES_FETCH_START = "PLACES_FETCH_START";
export const PLACES_FETCH_SUCCESS = "PLACES_FETCH_SUCCESS";
export const PLACES_FETCH_ERROR = "PLACES_FETCH_ERROR";
export const PLACES_FETCH_REFRESH = "PLACES_FETCH_REFRESH";
export const CITIES_FETCH_START = "CITIES_FETCH_START";
export const CITIES_FETCH_SUCCESS = "CITIES_FETCH_SUCCESS";
export const CITIES_FETCH_ERROR = "CITIES_FETCH_ERROR";
export const CITIES_FETCH_REFRESH = "CITIES_FETCH_REFRESH";