export const PLACES_FETCH_START = "PLACES_FETCH_START";
export const PLACES_FETCH_SUCCESS = "PLACES_FETCH_SUCCESS";
export const PLACES_FETCH_ERROR = "PLACES_FETCH_ERROR";
export const PLACES_FETCH_REFRESH = "PLACES_FETCH_REFRESH";