import {useEffect} from 'react';
import Head from 'next/head';
import ContentWrapper from '../../components/ContentWrapper';
import {useDispatch, useSelector} from 'react-redux';
import {placesFetch} from '../../redux/actions/places';
import PlaceCard from '../../components/PlaceCard';
import styles from '../../styles/PlacesList.module.css';


export default function PlacesList() {
    const dispatch = useDispatch();
    const placesIds = useSelector(state => state.places.placesIds);

    useEffect(() => {
        dispatch(placesFetch());
    }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContentWrapper>
          <div className={styles.card__wrapper}>
            {placesIds && placesIds.map(id => (
                <PlaceCard key={id} id={id}/>
            ))}
          </div>
      </ContentWrapper>
    </div>
  )
}