import Head from 'next/head';
import Link from 'next/link';
import ContentWrapper from '../components/ContentWrapper';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={'/places'}>
          <a>Mista</a>
        </Link>
        <br></br>
        <Link href={'/cities'}>
          <a>Města</a>
        </Link>
    </div>
  )
}