import Head from 'next/head';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import PlaceCard from '../components/PlaceCard';

import {useEffect} from 'react';
import { useDispatch } from 'react-redux';
import {dataFetch} from '../actions'
import { useSelector } from 'react-redux';


export default function Home() {
  const dispatch = useDispatch();
  const data = useSelector(state => state.data);
  console.log(data);

  useEffect(() => {
    dispatch(dataFetch());
  }, [dispatch]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <PlaceCard/>
    </div>
  )
}